name: Deploy Backend to Azure

on: # trigger on [main] branch
  push:
    branches: [ main ]
    paths: # only triggers if polls-backend or yaml file changes
      - 'polls-backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code # pull the repo backend so that it can later steps can access the polls-backend folder
      uses: actions/checkout@v4
    
    - name: Set up Python # this install python on the CI runner 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Create .deployment file for Oryx build
      working-directory: polls-backend
      run: |
        echo "[config]" > .deployment
        echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> .deployment
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'api-polls-test'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
        package: polls-backend


